version: '3.8'

services:
  mysql:
    image: mysql:5.7.41
    restart: always
    ports:
      - '3307:3306' # Burada 3307 portunu açtık Db bağlanmak için Ben Dbaver kullanıyorum.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_note:/data/db # Buradaki volume adı aşağıda tanımlanmalı

volumes:
  mysql_note: # Volume burada tanımlanmalı
